#!/usr/bin/env bash

# Author:
#   - Sergio Quijano Rey
#   - sergiquijano@gmail.com
# Description:
#   - Automatically sets display configuration on i3 systems
#   - Only supports two configurations
#       - Laptop display (monodisplay)
#       - Laptop display and 27'' display (dualdisplay)
#   - However, it is really easy to extend to more configurations
#   - It relies heavily on xrandr, for getting data and for setting the configuration
#   - You must have craeted an xrandr script fot setting up the configuration (ie. arandr)
# Versions:
#   - v1.0 - 03/06/2020 - First documented version

# Parameters
#===============================================================================
dual_display="$HOME/.i3/scripts/dualdisplay"
mono_display="$HOME/.i3/scripts/monodisplay"
error_log="$HOME/autodisplay.error"

# Var to hold the number of available displays
result=$(xrandr | grep -w "connected" | wc -l)

# We set the config depending on the number of displays available
if [ $result == 1 ]
then
    $mono_display
elif [ $result == 2 ]
then
    $dual_display
else
    echo "ERROR: $(date)"
    echo "No configuration available for this number of displays" >> $error_log
    echo "" >> $errro_log
fi
