#!/usr/bin/env python3
import subprocess
import re

acpi = subprocess.check_output('acpi', shell=True, stderr=subprocess.STDOUT).strip().decode('utf-8')

if acpi is '' or 'No support for device type:' in acpi:
    exit(0)

is_charging = re.search('Charging|Full', acpi)
percentages = []
for percentage in re.findall('(\d+)%', acpi):
    percentages.append(percentage)

icon = ''
output = icon + '  '
output += ' / '.join(percentages) 
output += '%'

print(output)
if is_charging:
    color = '#90a959'
    print()
    print(color)
elif int(percentages[-1]) <= 25:
    color = '#ac4142'
    print()
    print(color)
