#!/bin/sh

# Cambio la salida de las pantallas
xrandr --output HDMI2 --mode 1680x1050 --pos 0x0 --rotate normal --output HDMI1 --off --output DP1 --off --output eDP1 --primary --mode 1366x768 --pos 1680x0 --rotate normal --output VIRTUAL1 --off

# Vuelvo a cargar el fondo de pantalla predeterminado
wallpaper -c autumn_house.jpg
