#!/bin/sh
xrandr --output HDMI2 --off --output HDMI1 --off --output DP1 --off --output eDP1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output VIRTUAL1 --off

# Reload system bar
reload_polybar_script="$HOME/.config/polybar/launcher"
$reload_polybar_script
