#!/usr/bin/env bash

# Author:
#     Sergio Quijano Rey
#     sergiquijano@gmail.com
# Description:
#     Chooses a wallpaper at i3wm
# Version:
#     v1.0: first version, moved from python to bash
#     v1.1: added a choose option as a command parameter
# Dependencies:
#     feh
#     rofi

# Script parameters
#===============================================================================
source "/home/sergio/.bash_profile"
wallpaper_folder="$HOME/backgrounds/"
ROFI_THEME="/home/sergio/.i3/rofithemes/gruvbox.rasi"

# Script functions
#===============================================================================
function show_help() {
    echo "wallpaper"
    echo "\tWithout parameters: open ROFI to choose a wallpaper inside $wallpaper_folder"
    echo "\twallpaper -c <wallpaper>: chooses <wallpaper> as a wallpaper"
}

# The script
#===============================================================================

if [ $# == 0 ]
then
    # The image is selected from the wallpaper folder
    image=$(ls $wallpaper_folder | rofi -p "Choose a wallpaper:" -dmenu -config $ROFI_THEME)
else
    # We have a parameter, so we process it
    case "$1" in
        "-c")
            image=$2
            ;;
        *)
            echo "Bad parameter!"
            show_help
            exit
            ;;
    esac
fi

# The wallpaper is set using feh
feh --bg-scale $wallpaper_folder/$image
