#!/bin/bash

# Author:
#     Sergio Quijano Rey
#     sergiquijano@gmail.com
# Description:
#     Rofi web search, based on gotbletu websearch script
# Version:
#     v1.0 - 04/06/2019 - First documented an functional version
#     v1.1 - 18/10/2019 - Changed parameters, now using .bash_profile env vars

surfraw -browser=$BROWSER $(rofi -config $ROFI_THEME "rofi-surfraw-websearch: ")
