#!/usr/bin/env python3

# Author:
#     Sergio Quijano Rey
#     sergiquijano@gmail.com
# Description:
#     A simple program to make a slide wallpaper on i3-wm
# Version:
#     v1.0 01/10/2018 - First version
#     v2.0 27/11/2018 - Remove daemon utilitie and some bugs
#     v3.0 28/11/2018 - Just need to specify img dir

import random
import os

# Some functions
def choose_random_wallpaper(dir, opts, last_img = None):
    # The wallpaper img is chosen
    opt = random.choice(opts)
    img = dir + "/" + opt

    # The same wallpaper is discarded
    if img == last_img:
        return choose_random_wallpaper(dir, opts, last_img)
    else:
        # The i3-wm command is launch
        os.system("feh --bg-scale {}".format(img))
        return img

# The data of the wallpaper images
img_dir = "/home/sergio/GitProjects/misArchivos/Fondos_pantalla/LowPoly"
opts = os.listdir(img_dir)

# The actual algorithm
prev_img = choose_random_wallpaper(img_dir, opts)  # First time a wallpaper has to be chosen
