repo_base = "/home/sergio/GitRepos/dotfiles/"
system_base = "/home/sergio/"

[bash-rc]
repo_path = "./config_files/.bashrc"
system_path = ".bashrc"

[bash-profile]
repo_path = "./config_files/.bash_profile"
system_path = ".bash_profile"

[profile]
repo_path = "./config_files/.profile"
system_path = ".profile"

[bash-dotfiles]
repo_path = "./config_files/.bash_dotfiles"
system_path = ".bash_dotfiles"

[bash-aliases]
repo_path = "./config_files/.bash_aliases"
system_path = ".bash_aliases"

[bash-functions]
repo_path = "./config_files/.bash_functions"
system_path = ".bash_functions"

[bash-prompt]
repo_path = "./config_files/.bash_prompt"
system_path = ".bash_prompt"

[zsh-profile]
repo_path = "./config_files/.zprofile"
system_path = ".zprofile"

[zsh-dotfiles]
repo_path = "./config_files/.zsh_dotfiles"
system_path = ".zsh_dotfiles"

[gitconfig]
repo_path = "./config_files/.gitconfig"
system_path = ".gitconfig"

[i3-config]
repo_path = "./config_files/.i3"
system_path = ".i3"
sync_type = "dir"

[my-binaries]
repo_path = "./config_files/bin"
system_path = "bin"
sync_type = "dir"

[my-backgrounds]
repo_path = "./config_files/backgrounds"
system_path = "backgrounds"
sync_type = "dir"

[nvim-config]
repo_path = "./config_files/.config/nvim"
system_path = ".config/nvim"
sync_type = "dir"
ignore_paths = [
    "spell"
]

[alacritty-config]
repo_path = "./config_files/.config/alacritty"
system_path = ".config/alacritty"
sync_type = "dir"

[kitty-config]
repo_path = "./config_files/.config/kitty"
system_path = ".config/kitty"
sync_type = "dir"

[ranger-config]
repo_path = "./config_files/.config/ranger"
system_path = ".config/ranger"
sync_type = "dir"
ignore_paths = [
    "plugins/"
]

[polybar-config]
repo_path = "./config_files/.config/polybar"
system_path = ".config/polybar"
sync_type = "dir"

[tmux-config]
repo_path = "./config_files/.config/.tmux.conf"
system_path = ".tmux.conf"

[dunst]
repo_path = "./config_files/.config/dunst"
system_path = ".config/dunst"
sync_type = "dir"

[systemd]
repo_path = "./config_files/.config/systemd"
system_path = ".config/systemd"
sync_type = "dir"

[awesome]
repo_path = "./config_files/.config/awesome"
system_path = ".config/awesome"
sync_type = "dir"

[rofi]
repo_path = "./config_files/.config/rofi"
system_path = ".config/rofi"
sync_type = "dir"

[zellij-config]
repo_path = "./config_files/.config/zellij"
system_path = ".config/zellij"
sync_type = "dir"

[starship-config]
repo_path = "./config_files/.config/starship"
system_path = ".config/starship"
sync_type = "dir"

[NixOS-config]
repo_path = "./config_files/.config/nixos"
system_path = ".config/nixos"
sync_type = "dir"

[Nix-local-preferences]
repo_path = "./config_files/.config/nix"
system_path = "./config_files/.config/nix"
sync_type = "dir"

[More-Nix-local-preferences]
repo_path = "./config_files/.config/nixpkgs"
system_path = ".config/nixpkgs"
sync_type = "dir"
