#!/usr/bin/env bash

# Author:
#     Sergio Quijano Rey
#     sergiquijano@gmail.com
# Description:
#     Launcher for polybar
#     Code from https://github.com/polybar/polybar/wiki
# Version:
#     v1.0 - 23/08/2020 - First documented version

# Parameters
#===============================================================================
bar_name="mybar"

# Terminate already running bar instances
killall -q polybar

# Launch the bar
# -r means that changes to the config file are applied without the need of reloading the program
polybar -r $bar_name >>/tmp/mybar.log 2>&1 & disown
