# ============================ General configuration ============================
[open]
# This allows me to open directories with wsl so I end in the Windows File Explorer
prepend_rules = [
    { mime = "inode/directory", use = "open", run = "wsl-open $@" }
]

# ======================= Configuration to the git plugin =======================
[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
